




name: ML Pipeline CI

on:
  push:
    paths:
      - "../../Complete_MLOps_Bootcamp_With_10_End_To_End_ML_Projects/\
        Airflow_ASTRO/**"
  pull_request:
    paths:
      - "../../Complete_MLOps_Bootcamp_With_10_End_To_End_ML_Projects/\
        Airflow_ASTRO/**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # -------------------------
      # Python setup
      # -------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # -------------------------
      # Install dependencies
      # -------------------------
      - name: Install dependencies
        run: |
          pip install -r cd Complete_MLOps_Bootcamp_With_10_End_To_End_ML_Projects/Airflow_ASTRO



      # -------------------------
      # Run your pipeline
      # -------------------------
      - name: Run training
        run: |
          cd "Complete_MLOps_Bootcamp_With_10_End_To_End_ML_Projects/Airflow_ASTRO/exampledag"
          python Main_ML.py

      - name: Debug structure
        run: |
          pwd
          ls -R

      # -------------------------
      # Build Docker image (CI check only)
      # -------------------------
      - name: Build Docker image
        run: |
          docker build -t ml-pipeline-test "./Complete_MLOps_Bootcamp_With_10_End_To_End_ML_Projects/Airflow_ASTRO"
          

      - name: Run Docker container
        run: docker run ml-pipeline-test






